domain_path: C:\Users\ychna\xilinx_vivado\PFET_System_v1.0\pfet_freertos_platform\export\pfet_freertos_platform\sw\freertos_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\freertos_hello_world
template: freertos_hello_world
lang: c
