domain_path: C:\Users\ychna\xilinx_vivado\PFET_System_v1.0\pfet_standalone_platform\export\pfet_standalone_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
