# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xilinx_vivado/Zybo-Z7-Master.xdc

# Block Designs: bd/pfet_system/pfet_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pfet_system || ORIG_REF_NAME==pfet_system} -quiet] -quiet

# IP: bd/pfet_system/ip/pfet_system_axi_gpio_0_0/pfet_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pfet_system_axi_gpio_0_0 || ORIG_REF_NAME==pfet_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/pfet_system/ip/pfet_system_rst_ps7_0_50M_0/pfet_system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pfet_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==pfet_system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/pfet_system/ip/pfet_system_axi_smc_0/pfet_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pfet_system_axi_smc_0 || ORIG_REF_NAME==pfet_system_axi_smc_0} -quiet] -quiet

# IP: bd/pfet_system/ip/pfet_system_processing_system7_0_2/pfet_system_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pfet_system_processing_system7_0_2 || ORIG_REF_NAME==pfet_system_processing_system7_0_2} -quiet] -quiet

# XDC: c:/Users/ychna/xilinx_vivado/PFET_System_v1.0/PFET_System_v1.0.gen/sources_1/bd/pfet_system/pfet_system_ooc.xdc
