# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ychna/xilinx_vivado/PFET_System_v1.0/PFET_System_v1.0.srcs/sources_1/bd/pfet_system/ip/pfet_system_processing_system7_0_2/pfet_system_processing_system7_0_2.xci
# IP: The module: 'pfet_system_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ychna/xilinx_vivado/PFET_System_v1.0/PFET_System_v1.0.gen/sources_1/bd/pfet_system/ip/pfet_system_processing_system7_0_2/pfet_system_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfet_system_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/ychna/xilinx_vivado/PFET_System_v1.0/PFET_System_v1.0.srcs/sources_1/bd/pfet_system/ip/pfet_system_processing_system7_0_2/pfet_system_processing_system7_0_2.xci
# IP: The module: 'pfet_system_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ychna/xilinx_vivado/PFET_System_v1.0/PFET_System_v1.0.gen/sources_1/bd/pfet_system/ip/pfet_system_processing_system7_0_2/pfet_system_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfet_system_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
